name: Flutter Android Build

on:
  push:
    branches:
      - main
      - feature/day-1-foundation

  pull_request:
    branches:
      - main
      - feature/day-1-foundation

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear Gradle Cache
        run: |
          rm -rf ~/.gradle/caches

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.6'
          channel: stable

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flute-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk